language: python

env:
  - PYVER="2.7"
  - PYVER="3.4"
  - PYVER="3.5"
  - PYVER="3.6"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - which pip

  - conda create -q -n splinart-env python=$PYVER
  - source activate splinart-env
  - pip install -r requirements.txt
  - python setup.py install

script:
  - pytest --pylint --pylint-rcfile=.pyrcfile --pylint-error-types=EF splinart
  - cd tests
  - pytest --cov=splinart

after_success:
  - codecov  -e $PYVER

